# project.yml
packages:
  - name: toutbox-reversa-v2
    functions:
      - name: ocorrencias
        main: "dist/index.js"
        runtime: nodejs:18
        web: true
        files:
        - dist/**
        - package.json
        - package-lock.json
