import {
  mysqlTable,
  int,
  varchar,
  date,
  text,
  decimal,
  datetime,
  uniqueIndex,
  index,
} from "drizzle-orm/mysql-core";

export const preListaPostagem = mysqlTable(
  "pre_lista_postagem",
  {
    id: int("id").autoincrement().notNull().primaryKey(),
    codigoUnico: varchar("codigo_unico", { length: 100 }).default("NULL"),
    numeroPedido: varchar("numero_pedido", { length: 45 }),
    canal: varchar("canal", { length: 50 }).default("NULL"),
    usuario: varchar("usuario", { length: 255 }),
    dataCriacao: date("data_criacao"),
    ordemVenda: varchar("ordem_venda", { length: 100 }).default("NULL"),
    fornecimento: varchar("fornecimento", { length: 100 }).default("NULL"),
    coletaClienteNome: varchar("coleta_cliente_nome", { length: 255 }),
    coletaClienteCgc: varchar("coleta_cliente_cgc", { length: 100 }).default(
      "NULL",
    ),
    coletaClienteContato: varchar("coleta_cliente_contato", {
      length: 60,
    }).default("NULL"),
    coletaEndereco: text("coleta_endereco"),
    coletaLat: varchar("coleta_lat", { length: 20 }),
    coletaLon: varchar("coleta_lon", { length: 20 }),
    entregaNome: varchar("entrega_nome", { length: 255 }),
    entregaSobrenome: varchar("entrega_sobrenome", { length: 255 }),
    entregaContato: text("entrega_contato").default("NULL"),
    entregaCgc: text("entrega_cgc").default("NULL"),
    entregaCidade: varchar("entrega_cidade", { length: 255 }).default("NULL"),
    entregaNumero: varchar("entrega_numero", { length: 100 }).default("NULL"),
    entregaLogradouro: text("entrega_logradouro"),
    entregaBairro: varchar("entrega_bairro", { length: 255 }).default("NULL"),
    entregaComplemento: varchar("entrega_complemento", { length: 255 }),
    entregaUf: varchar("entrega_uf", { length: 2 }),
    entregaCep: varchar("entrega_cep", { length: 10 }),
    entregaLat: varchar("entrega_lat", { length: 20 }),
    entregaLon: varchar("entrega_lon", { length: 20 }),
    nfSerie: varchar("nf_serie", { length: 100 }).default("NULL"),
    nfNumero: varchar("nf_numero", { length: 100 }).default("NULL"),
    nfChave: varchar("nf_chave", { length: 100 }).default("NULL"),
    valorNota: decimal("valor_nota", { precision: 10, scale: 2 }),
    volume: int("volume"),
    peso: decimal("peso", { precision: 10, scale: 2 }),
    aceito: int("aceito").default(0),
    idEntrega: int("id_entrega"),
    payload: text("payload"),
    aceitoData: datetime("aceito_data", { mode: "string" }),
    aceitoUsuario: varchar("aceito_usuario", { length: 255 }),
    sla: int("sla"),
    valorFrete: decimal("valor_frete", { precision: 10, scale: 2 }),
    previsaoEntrega: date("previsao_entrega"),
    idOperacao: int("id_operacao"),
    origemUf: varchar("origem_uf", { length: 100 }),
    entregaAutorizacao: varchar("entrega_autorizacao", { length: 255 }),
    entregaRastreio: varchar("entrega_rastreio", { length: 255 }),
    centroCodigo: varchar("centro_codigo", { length: 100 }),
    centroNome: varchar("centro_nome", { length: 100 }),
    dataAgendamento: datetime("data_agendamento", { mode: "string" }),
    agendada: int("agendada").default(0),
    responsavelRecebimento: varchar("responsavel_recebimento", { length: 255 }),
    senhaVerificacao: varchar("senha_verificacao", { length: 255 }),
    tipoOperacao: varchar("tipo_operacao", { length: 100 }),
    tipoDevolucao: varchar("tipo_devolucao", { length: 3 }),
    cartaoPostagem: varchar("cartao_postagem", { length: 150 }),
    codigoAdministrativo: varchar("codigo_administrativo", { length: 150 }),
    contratoCorreios: varchar("contrato_correios", { length: 150 }),
    periodoEntregaAgendamento: varchar("periodo_entrega_agendamento", {
      length: 150,
    }),
    cluster: varchar("cluster", { length: 150 }),
    tecnologiaDeAcesso: varchar("tecnologia_de_acesso", { length: 150 }),
    acronimo: varchar("acronimo", { length: 50 }),
    entregaEmail: varchar("entrega_email", { length: 255 }),
    coletaCep: varchar("coleta_cep", { length: 20 }),
    entregaTelefoneFixo: varchar("entrega_telefone_fixo", { length: 155 }),
    entregaTelefoneAdicional: varchar("entrega_telefone_adicional", {
      length: 255,
    }),
  },
  (table) => [
    uniqueIndex("id_UNIQUE").on(table.id),
    index("pre_lista_postagem_id_entrega_IDX").on(
      table.idEntrega,
    ),
    index("pre_lista_postagem_nf_chave_IDX").on(table.nfChave),
    index("idx_plp_status").on(table.aceito),
    index("idx_plp_data").on(table.dataCriacao),
    index("idx_plp_canal").on(table.canal),
    index("idx_plp_operacao").on(table.idOperacao),
    index("idx_plp_cluster").on(table.cluster),
    index("idx_plp_agendada").on(table.agendada),
    index("idx_plp_cep").on(table.entregaCep),
    index("idx_plp_nome").on(
      table.entregaNome,
      table.entregaSobrenome,
    ),
  ],
);
