import {
  bigint,
  char,
  datetime,
  int,
  tinyint,
  longtext,
  mediumtext,
  mysqlTable,
  varchar,
} from "drizzle-orm/mysql-core";

export const operationsSchema = mysqlTable("_1_database_1_collection_13", {
  _id: int().primaryKey(),
  _uid: char({ length: 255 }).notNull(),
  _createdAt: datetime(),
  _updatedAt: datetime(),
  _permissions: mediumtext(),
  sigla: varchar({ length: 30 }),
  nome: varchar({ length: 100 }),
  codigo_atividade_padrao: varchar({ length: 100 }),
  codigo_atividade_padrao_backoffice: varchar({ length: 100 }),
  operador_regionais_id: longtext(),
  dias_baixa_automatica: bigint({ mode: "number" }),
  dias_validade_numero_serie: bigint({ mode: "number" }),
  dias_validacao_operacao_fiber_wttx: bigint({ mode: "number" }),
  validar_equipamento: tinyint(),
  enviar_email: tinyint(),
  digito_manual: tinyint(),
  cpf_cnpj: varchar({ length: 20 }),
  ie: varchar({ length: 20 }),
  cep: varchar({ length: 12 }),
  cidade: varchar({ length: 60 }),
  uf: varchar({ length: 2 }),
  bairro: varchar({ length: 256 }),
  logradouro: varchar({ length: 256 }),
  numero: varchar({ length: 20 }),
  complemento: varchar({ length: 256 }),
  email: varchar({ length: 254 }),
  telefone_1: varchar({ length: 20 }),
  telefone_2: varchar({ length: 20 }),
});
