import {
  mysqlTable,
  varchar,
  bigint,
  mediumtext,
  datetime,
  int,
  char,
} from "drizzle-orm/mysql-core";

export const ordersSchema = mysqlTable("_1_database_1_collection_51", {
  _id: int().primaryKey(),
  _uid: char({ length: 255 }).notNull(),
  _createdAt: datetime(),
  _updatedAt: datetime(),
  _permissions: mediumtext(),
  numero_ba: varchar({ length: 256 }),
  nome: varchar({ length: 256 }),
  cpf_cnpj: varchar({ length: 20 }),
  telefone_1: varchar({ length: 20 }),
  telefone_2: varchar({ length: 20 }),
  telefone_3: varchar({ length: 20 }),
  telefone_4: varchar({ length: 20 }),
  telefone_5: varchar({ length: 20 }),
  email: varchar({ length: 256 }),
  observacao: varchar({ length: 256 }),
  tipo_ocorrencia_id: varchar({ length: 55 }),
  cep: varchar({ length: 20 }),
  cidade: varchar({ length: 120 }),
  uf: varchar({ length: 2 }),
  bairro: varchar({ length: 256 }),
  logradouro: varchar({ length: 256 }),
  numero: varchar({ length: 30 }),
  complemento: varchar({ length: 256 }),
  contato: varchar({ length: 256 }),
  instancia: varchar({ length: 256 }),
  data_agendamento: bigint({ mode: "number" }),
  data_agendamento_fim: bigint({ mode: "number" }),
  criacao: bigint({ mode: "number" }),
  periodo_agendamento: varchar({ length: 50 }),
  codigo_rastreio: varchar({ length: 70 }),
  origem_agendamento: varchar({ length: 70 }),
  cobranca_cep: varchar({ length: 20 }),
  cobranca_cidade: varchar({ length: 120 }),
  cobranca_uf: varchar({ length: 2 }),
  cobranca_bairro: varchar({ length: 256 }),
  cobranca_logradouro: varchar({ length: 256 }),
  cobranca_numero: varchar({ length: 30 }),
  cobranca_complemento: varchar({ length: 256 }),
  cobranca_contato: varchar({ length: 256 }),
  endereco_referencia: varchar({ length: 256 }),
  parceiro_id: varchar({ length: 50 }),
  atividade_id: varchar({ length: 50 }),
  operadora_id: varchar({ length: 50 }),
  usuario_id: varchar({ length: 50 }),
  progresso: varchar({ length: 50 }),
  importacao_id: varchar({ length: 50 }),
  protocolo_entrega_id: varchar({ length: 256 }),
  cluster: varchar({ length: 256 }),
  assinatura: varchar({ length: 50 }),
  quantidade_equipamento: bigint({ mode: "number" }),
});
