import {
  bigint,
  char,
  datetime,
  int,
  mediumtext,
  mysqlTable,
  varchar,
} from "drizzle-orm/mysql-core";

export const orderHistorySchema = mysqlTable("_1_database_1_collection_47", {
  _id: int().primaryKey().autoincrement().notNull(),
  _uid: char({ length: 255 }).notNull(),
  _createdAt: datetime(),
  _updatedAt: datetime(),
  _permissions: mediumtext(),
  data_criacao: bigint({ mode: "number" }),
  descricao: varchar({ length: 256 }),
  tipo_ocorrencia_id: varchar({ length: 50 }),
  usuario_id: varchar({ length: 50 }),
  usuario_nome: varchar({ length: 80 }),
  parceiro_id: varchar({ length: 50 }),
  parceiro_nome: varchar({ length: 255 }),
  ordem_servico_id: varchar({ length: 50 }),
  ordem_servico_item_id: varchar({ length: 50 }),
  latitude: varchar({ length: 50 }),
  longitude: varchar({ length: 50 }),
  data_agendamento: bigint({ mode: "number" }),
  data_agendamento_fim: bigint({ mode: "number" }),
  familia_equipamento_id: varchar({ length: 55 }),
  numero_ba: varchar({ length: 256 }),
  codigo_telefonica: varchar({ length: 30 }),
  status: bigint({ mode: "number" }),
  foto_id: varchar({ length: 50 }),
  id_sinc: varchar({ length: 50 }),
  resinc: int(),
});
